version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio-server
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    networks:
      - epicevents-network

  mongodb:
    image: mongo:latest
    container_name: mongodb-server
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - epicevents-network

volumes:
  minio-data:
  mongo-data:

networks:
  epicevents-network:
    driver: bridge
